author: Matthew Evans
title: Matthew Evans
name: Matthew Evans
email: me388[at]cam.ac.uk
description: PhD student at the University of Cambridge, working on crystal structure prediction for energy storage materials.
show_downloads: false
markdown: kramdown
theme: minima 
twitter_username: funroll_loops
github_username: ml-evs
bitbucket_username: ml-evs
departmental_website: http://www.tcm.phy.cam.ac.uk/profiles/me388/
scholar_id: 3aG55qYAAAAJ&hl
orcid_id: 0000-0002-1182-9098
exclude:
    - Gemfile
    - Gemfile.lock
