author: Matthew Evans
title: Matthew Evans
name: Matthew Evans
email: matt[at]ml-evs.science
description: Postdoc at UCLouvain, working in computational materials science.
show_downloads: false
markdown: kramdown
theme: minima
twitter_username: funroll_loops
github_username: ml-evs
scholar_id: 3aG55qYAAAAJ&hl
orcid_id: 0000-0002-1182-9098
exclude:
    - Gemfile
    - Gemfile.lock
    - blog/
plugins:
    - jekyll-seo-tag
